replicas: 1
sql: 
  name: mysql
  replicaCount: 1
  appname: sql
  container:
    image: anandshivam44/mysql
    port: 3306
    env:
      name: sql-secret
  service:
    type: ClusterIP
    port: 3306
    name: sql-service
    protocol: TCP
  volume:
    name: mysql-persistent-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/mysql
    pvc:
      accessMode: ReadWriteOnce
      storage: 2Gi
    pvname: mysql-pv-claim
  config:
    name: sql-configmap
    data:
      - key: key
        value: value
