apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: crud-api-python
          image: anandshivam44/crud-api-python
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: sql-root-username
            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: sql-root-password
            - name: MYSQL_DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: sql-root-database-name
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: sql-configmap
                  key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: flaskapi-service
spec:
  selector:
    app: flaskapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
