apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sql
        image: anandshivam44/mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: sql-root-username
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: sql-secret
              key: sql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
