apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sql.volume.pvname }}
  labels:
    app: {{ .Values.sql.name }}
spec:
  accessModes:
    - {{ .Values.sql.volume.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.sql.volume.pvc.storage }}
