apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flaskapi.name }}
  labels:
    app: {{ .Values.flaskapi.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.flaskapi.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskapi.appname }}
    spec:
      containers:
        - name: crud-api-python
          image: {{ .Values.flaskapi.container.image }}
          ports:
            - containerPort: {{ .Values.flaskapi.container.port }}
          # envFrom:
          #   {{- range .Values.flaskapi.container.config }}
          #   - configMapRef:
          #       name: {{ .name }}
          #   {{- end}}
          env:
            {{- range .Values.flaskapi.config.data}}
            - name: {{ .key}}
              value: {{ .value}}
            {{- end}}



