apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flaskapi.service.name }}
spec:
  selector:
    app: {{ .Values.flaskapi.appname }}
  type: {{ .Values.flaskapi.service.type }}
  ports:
    - protocol: {{ .Values.flaskapi.service.protocol }}
      port: {{ .Values.flaskapi.service.port }}
      targetPort: {{ .Values.flaskapi.service.port }}
      nodePort: {{ .Values.flaskapi.service.nodePort }}